### ISSUE TITLE
Semantic CSS classes

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#10]
Maybe this is because of using Bootstrap for a long while, but I'm thinking of alert in semantic terms, e.g. "success" or "warning" or "error".

The problem is, the CSS classes are colors, and it's not obvious how they correspond to the alert types:

    .s-alert-blue, .s-alert-green, .s-alert-yellow, .s-alert-red

(e.g. is success blue or green?)

My suggestion would be to rename the CSS classes to describe the *type* of the alert, e.g.

```css
.s-alert-effect-scale.s-alert-error {
    /* CSS rules for an error displayed using the "scale" effect
}
```

Also, ideally the alert type would be specified first in examples, since the *style* of displaying an alert is secondary to its *nature*/*type*.

**Comment by juliancwirko** [comment]
At the beggining it was called 'red condition', 'blue condition' etc. It was then renamed into 'warning', 'info' etc. I definately need to rename the css classes.

Thanks for all your suggestions (waiting for more :) ). I think it is a material for a bigger refactor. Maybe I should put it all in version 3.0.0. I'll think about it, but all your suggestions are of course worth implementing.

**Comment by juliancwirko** [comment]
Ok, it is done in v2.1.0

**Comment by dandv** [comment]
Confirmed; thanks again!
