### ISSUE TITLE
Is standard config effect really "scale"?

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#12]
https://github.com/juliancwirko/meteor-s-alert#salert-configuration says the standard config effect is 'scale' but if I create a new project and only add the main package (without any effects), then `sAlert.error('Boom! Something went wrong!')` won't display any info in the browser console to load the scale effect.

`sAlert.error('Boom! Something went wrong!', {effect: 'scale'});` *will* correctly display `Install "scale" effect by running "meteor add juliancwirko:s-alert-scale"`.

Maybe the default should be "no effect".

**Comment by juliancwirko** [comment]
There is `effect: ''` in standard config, and in readme it is configuration example only. 
Anyway, we need message here to. I will add it soon. Good point.

**Comment by juliancwirko** [comment]
done in v2.1.1

**Comment by dandv** [comment]
Correct, [the default effect is `''`](https://github.com/juliancwirko/meteor-s-alert/blob/master/client/s-alert.js#L49).What I mean is that the README should be updated at https://github.com/juliancwirko/meteor-s-alert#salert-configuration to say `effect: ''`.

**Comment by juliancwirko** [comment]
Done.
