### ISSUE TITLE
Automatically center text if the position is `top` or `bottom`?

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#13]
I was wondering if it would make sense for the text to be automatically centered if the position is `top` or `bottom`. What do you think?

**Comment by juliancwirko** [comment]
Hmmm, personaly I like it on the left ;) 
I think it is something which can be simply styled in app by `.s-alert-box {text-align: center}`, so maybe we could leave it as is, what you think?

**Comment by dandv** [comment]
Makes sense.
