### ISSUE TITLE
How is the alert id obtained?

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#15]
The README says

> id is from Meteor collection called sAlerts.collection (client only)

But how is this ID obtained? Does the user need to run `sAlert.collection.find()`? If so, the fields for that `find()` call should be documented, i.e. `messages` and `condition`. BTW `type` seems like a more intuitive name than `condition`.

Alternatively, the sAlert methods could return the ID of the alert they have just created:

    var warningThatWeWantToCloseLater = sAlert.warning('Please register');

**Comment by juliancwirko** [comment]
Oh, yes, this one is important too. 
I will return sAlert id in sAlert functions (exactly as you described here). 
This could be very useful for example when timeout is set to 'none' or big number and we want to close it from somewhere.

I will try to change `condition` into `type` in version 3.0.0.

**Comment by juliancwirko** [comment]
done in v2.1.1

**Comment by dandv** [comment]
Nice! Any chance for a simple package test file for this functionality?

**Comment by juliancwirko** [comment]
Yes, I tought about tests. I'll try to add some for version 3.0.0

**Comment by juliancwirko** [comment]
There are some tests now in version 2.3.3
