### ISSUE TITLE
Custom templates do not stack

### ISSUE THREAD

**Issue by jesseflorig** [juliancwirko/meteor-s-alert#19]
If I use the default template with `{{> sAlert}}` the alerts stack as expected. If I copy the default example from the documentation and make it a custom template, the templates overlap each other.

`{{> sAlert tempalte="customAlert"}`

Custom template

```
<template name="customAlert">
    <div class="s-alert-box s-alert-{{condition}} s-alert-{{position}} s-alert-effect-{{effect}} s-alert-show" id="{{_id}}">
        <div class="s-alert-box-inner">
            <p>{{message}}</p>
        </div>
        <span class="s-alert-close"></span>
    </div>
</template>
```

**Comment by juliancwirko** [comment]
Not good :/ I will test it and try to fix it ASAP. Thanks.

**Comment by juliancwirko** [comment]
Hey, I can't test it now, but I see here that you forgot about `style="{{boxPosition}}"` in main `s-alert-box` element.
This is my fault. It wasn't in the readme example.

```handlebars
<div class="s-alert-box s-alert-{{condition}} s-alert-{{position}} {{#if effect}}s-alert-effect-{{effect}}{{/if}} s-alert-show" id="{{_id}}" style="{{boxPosition}}">
    <div class="s-alert-box-inner">
        <p>{{#if isHtml}}{{{message}}}{{else}}{{message}}{{/if}}</p>
    </div>
    <span class="s-alert-close"></span>
</div>
```

**Comment by juliancwirko** [comment]
Ok, I have added some adjustments in version 2.3.4. It should work, just remember to add `style="{{boxPosition}}"`. Let me know if it works for you. Thanks.

**Comment by jesseflorig** [comment]
@juliancwirko :+1:  Thanks for looking into to this and resolving it! I apologize for not being active over the past 48 hrs :/

**Comment by juliancwirko** [comment]
Ok :) closing this one
