### ISSUE TITLE
Alert doesn't clear if I change browser tabs and come back

### ISSUE THREAD

**Issue by stevenhornung** [juliancwirko/meteor-s-alert#2]
Strange bug.. If the alert is open on one tab and I switch to another tab and come back, the alert banner doesn't go away and isn't closable.  

I'm using the stackslide effect.  This happens on chrome but not on safari.

**Comment by juliancwirko** [comment]
Hi, yes I have noticed it too. I think I know how to fix it. I will try soon..

**Comment by juliancwirko** [comment]
Ok, with version 1.0.1 it should close alerts immediately when it detects that you are on different browser tab.
It is published on Atmosphere.

**Comment by stevenhornung** [comment]
@juliancwirko works great!  Thanks for the quick fix
