### ISSUE TITLE
Keep the alerts on route change

### ISSUE THREAD

**Issue by VladShcherbin** [juliancwirko/meteor-s-alert#20]
How can the alerts stay on route change? For example I can log in and show the message for 3 seconds. But after 0.5 sec the route would change and the message would hide.

How can this be made ?

**Comment by juliancwirko** [comment]
Hey, take a look here: https://github.com/juliancwirko/meteor-s-alert/issues/5 and tell me what you think about this. I think this is the same question.

**Comment by VladShcherbin** [comment]
@juliancwirko yep, this is the same issue, that I have. But, what's about a case, when I don't use Autoform hooks and a router session thing seems like a dirty hack, don't you think so?

I just thought, this is a template, that won't flash on route change and stay consistent. The behaviour is strange and unpredictable for me. But maybe it's just me.

**Comment by juliancwirko** [comment]
I think I could add config option for this. `onRouteChangeClean: false` or something. Then if you have your `{{> sAlert}}` in the body or somewhere in the main layout it should persist. But this should be tested. I remember that there was a problem with closing alert box after route change. I will look into this.

**Comment by VladShcherbin** [comment]
@juliancwirko yes, that would be awesome. I have sAlert in the main layout, but it flushes on route change. Will wait for a workaround.

**Comment by juliancwirko** [comment]
@VladShcherbin Hey, update your sAlert package to 2.3.5 and set up `onRouteClose: false` in your config. Let me know how it works for you. You can read more in the readme https://github.com/juliancwirko/meteor-s-alert#using-with-routers Thanks!

**Comment by jmlv** [comment]
Greate! Thanks!

**Comment by VladShcherbin** [comment]
@juliancwirko yep, it is working now as I expect. Thank you!
