### ISSUE TITLE
stackable alerts

### ISSUE THREAD

**Issue by stevenhornung** [juliancwirko/meteor-s-alert#21]
I use stackslide stretched across the top for notifications.  In previous versions when multiple alerts popped up, they would stack on top of each other so the user only saw the latest one.  Now they stack down below each other and it looks odd for my use.

Is there any good way to have them not drop below each other and, instead, stack on each other like they used to?

Thanks

**Comment by juliancwirko** [comment]
Hey, you can run `sAlert.closeAll();` before sAlert calls. I think I could add config param for this use case too ;)

**Comment by stevenhornung** [comment]
That could be a temporary workaround but I'd really like to use it globally so something that I could configure how they stack would be ideal!  

Just to illustrate my problem: I add a top: 65px to push down the alert to popup below the top menu bar on my site.  So when there are multiples it adds that 65px between each alert so they are just spaced out and look odd.

**Comment by juliancwirko** [comment]
Ok, I will try to add something like `stack: false` maybe I should also add `offset` param. I will think about it. Thanks.

**Comment by stevenhornung** [comment]
That sounds great! Thanks a lot for the quick responses :D

**Comment by juliancwirko** [comment]
I am on it. Need some more time :)

**Comment by juliancwirko** [comment]
Hey, in version 2.4.0 there are `stack` (default true - enabled) and `offset` (default '0' - in pixels, top or bottom, depends on position type) params. You can check it out. More in the readme file.

**Comment by stevenhornung** [comment]
Just upgraded and it works perfectly!  Made use of both the stack and offset params.  Thanks a lot!
