### ISSUE TITLE
Adding sound

### ISSUE THREAD

**Issue by abdulahkam** [juliancwirko/meteor-s-alert#25]
Is there any way I can add sound for s-alert?
I think it is a cool package and need some improvement. I would like to contribute.
Thanks.

**Comment by juliancwirko** [comment]
Hey, this is quite interesting idea ;) I think it could use Web Audio API http://www.html5rocks.com/en/tutorials/webaudio/intro/ but i don't know if this should be a part of the sAlert package. Maybe we could write another package for playing audio on demand and integrate it by custom sAlert template helpers or onCreated/onRendered life cycle event (or even we could add support for it in sAlert config). But I think that it should be a separate package.

**Comment by abdulahkam** [comment]
Well, I thought we can add in the configuration like sAlert.danger("Kaboomm",{sound:"/sound/kaboom.wav"});

So, If we make a new package, it should be like extended version of sAlert? even just the configuration is different?

**Comment by juliancwirko** [comment]
Actually we don't need another package. We should be able to put `sound: 'path'` or `'audio: 'path'` (I prefer 'audio') in the config (there will be automaticaly 'sound' or 'audio' field in the sAlert.collection), and then we can use Web Audio API like: 
```javascript
sAlert.audio = new Audio('/audio_file.mp3'); // I think this should be initialized once (https://github.com/juliancwirko/meteor-s-alert/blob/master/client/s-alert.js)

sAlert.audio.load(); // I think this should be called when sAlert functions are fired (https://github.com/juliancwirko/meteor-s-alert/blob/master/client/s-alert-template.js#L68)
sAlert.audio.play(); // I think this should be called when sAlert functions are fired (https://github.com/juliancwirko/meteor-s-alert/blob/master/client/s-alert-template.js#L68)
```
I don't know exactly because I don't know audio API well (tests needed), but we need call  sAlert.audio.load() just before sAlert.audio.play() because we should clear all playing audio.

- mp3 should work in major browsers
- there should be also mp3 file in the `public` folder or it could be played from other server

This is not so much aditional code so we could integrate it in the sAlert main package.

I can look into it, but I don't know when exactly. So if you want you can try to play with it.

**Comment by abdulahkam** [comment]
But, what if, someone wants different sound for different event? Maybe it will be even cooler.

Sure thing. I will try to play with it within these two days. I hope I can make it work.

**Comment by juliancwirko** [comment]
You are right. We should create `sAlert.audio = new Audio('/path/to/file')` with different paths. It needs some tests, but of course it could be done.

**Comment by mvdmolen** [comment]
+1

**Comment by juliancwirko** [comment]
This is really nice idea for a new subpackage. I think soon (1-2 months) I will have some time for this. There will be some package cleaning too. I think there will be version 3.0 after all.

**Comment by sergiotapia** [comment]
That would be awesome. Imagine Facebook like notifications with a little 'ping' auto built.

**Comment by juliancwirko** [comment]
I'm on it. It is almost done. There will be no separate package but config param. It will be one path for one global audio file or object with particular paths to audio files for different alert conditions. Also you will be able to overwrite it with a single call like `sAlert.warning('warning msg', {beep: '/path-to/audio-file.ogg'})` You can put your audio files in the `public` folder or you can pass URL to file. Any other ideas are welcomed.

**Comment by mvdmolen** [comment]
++1! Thank you! :)

On Sat, Aug 15, 2015 at 2:00 PM, Julian Ćwirko <notifications@github.com>
wrote:

> I'm on it. It is almost done. There will be no separate package but config
> param. It will be one path for one global audio file or object with
> particular paths to audio files for different alert conditions. Also you
> will be able to overwrite it with a single call like sAlert.warning('warning
> msg', {beep: '/path-to/audio-file.ogg'}) You can put your audio files in
> the public folder or you can pass URL to file. Any other ideas are
> welcomed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliancwirko/meteor-s-alert/issues/25#issuecomment-131412023>
> .
>



-- 
Mark Vandermolen
3008 Dataw Lane
Indian Trail, NC 28079
(704) 684-9355

**Comment by juliancwirko** [comment]
Ok, there is a new version 3.0.0 
For how to use audio alerts check out updated readme: https://github.com/juliancwirko/meteor-s-alert#salert-configuration 

Let me know what you think. Thanks.

**Comment by mvdmolen** [comment]
So the sound is awesome. It took me some time to get it to work, because it refused to update to 3.0.0. I had to force the version file to pick the right version.

But here is a big follow up request. I MUST be able to SILENCE the alarm. A loop would also be nice, although I can get away with looping within a very long mp3 file.

Can silence (pause/stop) be implemented?

Fantastic job! Thanks!

**Comment by abdulahkam** [comment]
Thanks @juliancwirko

**Comment by juliancwirko** [comment]
@mvdmolen you mean that we should stop sound when the alert is closed by hand? 
I will test it and implement it later. For now it is better to use short audio files. Also if there will be some alerts one after another the sound will be restarted each time.

**Comment by mvdmolen** [comment]
@juliancwirko Correct. Stop when alert is closed. Overlapping alerts is perfect for me. If one alert closes the beep.mp3 should stop just for that one closed alert.

**Comment by juliancwirko** [comment]
Ok, it will be done soon.

**Comment by juliancwirko** [comment]
It should be fixed now. In version 3.1.0
