### ISSUE TITLE
Hide close button

### ISSUE THREAD

**Issue by Jargonius** [juliancwirko/meteor-s-alert#26]
It would be very nice to have the option to hide the close button on an alert by alert basis.  Then the user cannot close it but you could programatically close it.

**Comment by juliancwirko** [comment]
You can always use your [custom template](https://github.com/juliancwirko/meteor-s-alert#template-overwriting) without close button or hide it with css. I am not sure if we need another option in the configuration for this use case.

**Comment by Jargonius** [comment]
Thanks for the feedback!  I actually figured out that very solution.  I hid it with css and then I realized I could use the template with it's custom parameters to conditionally hide the button.
