### ISSUE TITLE
Uncaught TypeError: FlowRouter.middleware is not a function

### ISSUE THREAD

**Issue by lukeclifton** [juliancwirko/meteor-s-alert#28]
Getting the above error when using FlowRouter 2.0.1

I believe the following code needs updating to new FlowRouter 2.0 API. middleware API has been depreciated. Need to use triggers API instead. 

```javascript
// routers clean
Meteor.startup(function () {
    if (typeof Iron !== 'undefined' && typeof Router !== 'undefined') {
        Router.onStop(function () {
            sAlert.collection.remove({onRouteClose: true});
        });
    }
    if (typeof FlowRouter !== 'undefined') {
        FlowRouter.middleware(function (path, next) {
            sAlert.collection.remove({onRouteClose: true});
            next();
        });
    }
});
```

**Comment by juliancwirko** [comment]
Hey, thanks for pointing this out. You have the old code here. There is newest including triggers (https://github.com/juliancwirko/meteor-s-alert/blob/master/client/s-alert.js#L89).

But I think the problem might be different. Anyway, let me know if updating to s-alert 2.4.1 helps and I will test it asap.

**Comment by lukeclifton** [comment]
Hey. Sorry,  i did update but looks like my app didn't use the new version until i forced it too with juliancwirko:s-alert@2.4.1. This has sorted it now and the error has gone. Thanks.

**Comment by juliancwirko** [comment]
You can also try to remove the package 'meteor remove juliancwirko:s-alert' and add it once again 'meteor add juliancwirko:s-alert' then it should install the newest version. 

I think I need to bump versions of s-alert in subpackages with effects.

Anyway, I am glad that this helps.
