### ISSUE TITLE
stackslide banner not closable occasionally

### ISSUE THREAD

**Issue by stevenhornung** [juliancwirko/meteor-s-alert#3]
I've seen a few instances where the alert will come down and if I go to another route while the transition is happening, the alert will not go away.  It sticks to the top and I can't even close out of it.  The only way to get rid of it at this point is to refresh the page.

**Comment by juliancwirko** [comment]
Hmmm, I need to test it.
Quick fix is to clear alerts with Iron Router onBeforeAction hook:
```
Router.onBeforeAction(function () {
    sAlert.closeAll();
    this.next();
});
```
I will keep you posted.

**Comment by juliancwirko** [comment]
Ok, it should work now. Version 1.1.2. You can test it.
