### ISSUE TITLE
Proposal: send alerts from the server

### ISSUE THREAD

**Issue by voidale** [juliancwirko/meteor-s-alert#30]
Hey Julian,

I had a great idea and I actually need something like this I was wondering if you like it and want to implement it. It can be really useful if it's possible to send alerts such as an error or success from the server directly to the user, for example if a cronjob runs on the server and does something and we have a problem that requires the user's action like changing settings etc... we can send an alert to the user directly to let him know. What you think?

**Comment by juliancwirko** [comment]
Hi, I am not sure exactly how it might work because now you can throw an error in Meteor server method and simply catch it on the client and run sAlert. I'll give you an example:

Server: 
```javascript
Meteor.methods({
    mailSubscribe: function (repoId) {
        var userId = this.userId;
        if (userId && repoId) {
            Meteor.users.update({_id: userId}, {$addToSet: {'subscriptions': repoId}});
        }
    }
})
```

Client:
```javascript
Meteor.call('mailSubscribe', repoId, function (err) {
    if (!err) {
        sAlert.success('You are now subscribing You will be reciving e-mail alerts.');
    } else {
        sAlert.error('Ups, something went wrong: ' + err.toString());
        //or: sAlert.error(err);
    }
});
```

If you need some more logic you can also use [collection hooks](https://atmospherejs.com/matb33/collection-hooks) on the client. 

I wonder if this is necessary to create something on the server. But you can create demo repo with such use case. I can't see it right now :)

**Comment by voidale** [comment]
@juliancwirko 
yeah It might seem odd use case but I thought about sending notification about server side functions without meteor methods. 

Maybe it should be more of a separate package (or maybe this logically incorrect way of doing things lol) where you display on top persistent bar with notification like "You're missing timezone settings, please correct it now" and we added this notification because when we tried to do server side cronjob we detected the user doesn't have any timezone settings. (Yeah we can require the user to submit the timezone as a must) 

but I'm trying to send notifications in more of like if we had a database insert failure or any unexpected way it has happened and the document wasn't saved and it depends on 2 different collections some where there is a missing link. 

So a way to notify the user is great for unexpected things. But yeah the more I think about the more it's gets complicated and maybe not really a good way of doing things

**Comment by dtruel** [comment]
I'd like to see this too - send an alert based on a schedule

**Comment by juliancwirko** [comment]
This package works on the client side. You have global sAlert.success(...), sAlert.error(...) etc. functions which can be fired in the browser. The way you want to fire this functions is up to you. So you can do whatever you want and just use these functions on the client side. I'm afraid I don't see the possibility to include it in the package right now. Maybe you are right and there is needed some other functionality (maybe a new package) which will do that.
