### ISSUE TITLE
Stack up spacing & limit

### ISSUE THREAD

**Issue by dominicarrojado** [juliancwirko/meteor-s-alert#31]
Hope you could add stack up spacing (spaces between each stack) and maybe the stack up limit (after 3 stacks remove the 1st stack so it wont spam). Thanks!

**Comment by juliancwirko** [comment]
Yes I'll look into it. Thanks.

**Comment by dominicarrojado** [comment]
Thanks too. :+1: Cool package btw

**Comment by juliancwirko** [comment]
It is added in version 3.1.0

**Comment by dominicarrojado** [comment]
Wow thanks man!

**Comment by dominicarrojado** [comment]
Btw, how can I update the package?

**Comment by dominicarrojado** [comment]
Yo man I've updated it! Hmm, hope it didn't close all right away when stack up to 3, what I had in mind was close only the 1st stack then all goes down, I just like that effect rather than close all, I have done a work around when you still haven't updated the package and it was like that. Hope you would do that. Also, there's no effect when using sAlert.closeAll(); they just disappear. Hehe thanks man thanks!

**Comment by juliancwirko** [comment]
Hi, yes these are very good ideas. I will try to work on it more. Thanks.

**Comment by juliancwirko** [comment]
Ok, in version 3.1.1 when you use stack limit the the last element will be deleted when there will be to many alerts (also with animation) but 'sAlert.clearAll()' is intended to remove all alerts immediately. Anyway it is not used here. Let me know if this is what you had in mind.

**Comment by dominicarrojado** [comment]
Cool. Will check it out!

**Comment by juliancwirko** [comment]
I will close it for now. If you want you can still comment here. Thanks.

**Comment by sephirothmk** [comment]
I'm doing this to prevent multiple alerts appearing when a user is trigger-happy with his mouse. However, it doesn't work.

sAlert.error("Please input a valid email!", {
                stack: {
                    spacing: 0,
                    limit: 1
                }
            });

**Comment by juliancwirko** [comment]
@sephirothmk if you need only one alert, you can disable stacking by: `stack: false`, anyway I've done some tests and it seems to work well for me, even with your configuration, weird :/

**Comment by sephirothmk** [comment]
Strangely, `stack: false` behaves the same as `stack: true`, it just renders the alerts on top of each other. I'm also using `juliancwirko:s-alert-bouncyflip` maybe this is related to the issue I'm having

**Comment by juliancwirko** [comment]
You can go here: http://s-alert-demo.meteor.com/ and open the console and paste this couple of times: 

```
sAlert.error("Please input a valid email!", {effect: 'bouncyflip', stack: false });
```
for me it works ok. This will not block alerts. This will just display them in the same place.
