### ISSUE TITLE
Any way to override placement with a configuration parameter?

### ISSUE THREAD

**Issue by SparserLogic** [juliancwirko/meteor-s-alert#33]
Could we give a particular x/y position to create the alert?

**Comment by juliancwirko** [comment]
For now you can have offset config param, also you can customize your css file. For now I don't plan to add x/y positioning. I think this is not so widely needed and it might be problematic.

**Comment by SparserLogic** [comment]
> For now you can have offset config param

Okay, thanks, I will use this.

**Comment by juliancwirko** [comment]
Also soon there will be something like stack.spacing in the config. So you will be able to do something like: 

```
(...)
offset: 60, //for first alert
stack: {
    spacing: 60 // for all other alerts
}
(...)
```
The spacing param will also add spacing on the left and right. So basically it is very similar.

**Comment by juliancwirko** [comment]
Ok it is ready in version 3.1.0

**Comment by SparserLogic** [comment]
Awesome. Thank you.

**Comment by SparserLogic** [comment]
If you're open to requests, a nice feature would be to be able to anchor alerts to a specific element.

For instance, I would like my users to have the option to drag a button and drop it wherever they would like the alerts to show up. The reasoning is that some user's have small display windows and alerts can sometimes cover important things, so allowing them to be draggable would be really nice.
