### ISSUE TITLE
Request: Add onClose handler to the options list

### ISSUE THREAD

**Issue by SparserLogic** [juliancwirko/meteor-s-alert#34]
I would like to take actions against my stored data whenever the user clicks to close an alert, or if the alert expires naturally due to timeout.

I can currently achieve the former with a custom template and a piggyback jquery click handler but it feels like a bit of a hack and I'd prefer a real event handler option for when the alert is closed.

**Comment by juliancwirko** [comment]
Hmmm, have you looked on [collection hooks package](https://github.com/matb33/meteor-collection-hooks) ? I think it will solve your use case. sAlert collection is called 'sAlert.collection' I think you could hook your actions when documents (alerts) are removed.

Let me know if this is sufficient for you. I would rather not to add more logic here, especially if there is a package for it. But of course if this is not enought I could add some event triggers.

**Comment by SparserLogic** [comment]
Fantastic. Yes, we're already using it and that will do nicely.

Now all I need to do is figure out your data model.

**Comment by juliancwirko** [comment]
Ok, so I will close this task for now. If you have further questions you can open a new issue.
