### ISSUE TITLE
[fixed] Alerts at top concealed by Bootstrap navbar

### ISSUE THREAD

**Issue by Alveoli** [juliancwirko/meteor-s-alert#35]
I guess some padding is needed within the CSS - can this be handled automatically by the package?

![bootstrap](https://cloud.githubusercontent.com/assets/8811975/9879947/7bb85e50-5bc1-11e5-8cfb-2a913c1b176d.PNG)

I'm using a standard Bootstrap navbar.

**Comment by tab00** [comment]
Maybe it should appear on top of the navbar instead of under it, like [natestrauser:connection-banner](https://atmospherejs.com/natestrauser/connection-banner).

**Comment by juliancwirko** [comment]
Hi, you can configure your `offset`. See the documentation: http://s-alert.meteor.com/  Also I think you might customize your z-index in css so it could appear on top of the navbar.

**Comment by Alveoli** [comment]
Hi @juliancwirko thanks for that - I didn't notice it was a feature - maybe new?

Anyway I used it, and it seems to have caused a strange problem - see gif animation.  I have a bottom-right alert appear first (no offset) then a top-right alert with offset: 120. It's weird that the initial positioning is incorrect, then it's only fixed when the first alert disappears.

![strange-offset](https://cloud.githubusercontent.com/assets/8811975/10074598/d0f24d14-62c8-11e5-9522-ddb09e5e1309.gif)

**Comment by juliancwirko** [comment]
Hi, yes this is strange behaviour. I will try to fix it.

**Comment by juliancwirko** [comment]
It should be ok now. (In version v3.1.2)

**Comment by juliancwirko** [comment]
I close it for now. If you want you can still comment here. Thanks!

**Comment by Alveoli** [comment]
Seems fixed to me - thanks!
