### ISSUE TITLE
Click events on alert - Not working

### ISSUE THREAD

**Issue by amnevins** [juliancwirko/meteor-s-alert#37]
This is a great alerts package, to anyone considering using it.  
My problem is:
It seems when I use html markup in the alert as so 
e.g. 

sAlert.info(secretMessage.Name + '<*br> <*a class="mapClick">View Profile<*/a>', {html: true});

*ignore asterik in <*/a> 
and add a click listener

e.g.  

'click .mapClick' : function(e) {
e.preventDefault();
console.log("clicked");
}

I can't get the event to fire.  Is there a way to target the sAlert for an event?  I have tried using various inherited classes such as 'click .s-alert-box' , and have been unsuccessful.

Any help is appreciated, thanks!

**Comment by juliancwirko** [comment]
Hi, I'll test it tomorrow. I'll keep you posted here.

**Comment by juliancwirko** [comment]
Ok, so I have tested it and it works for me. I have: 

```html
<body>
    {{> sAlert}}
</body>
```

```js
Template.sAlert.events({
    'click .alert-click-class': function (e) {
        e.preventDefault();
        console.log('Alert link clicked!');
    }
});
```
and I am calling for example this:

```js
sAlert.warning('<a href="#" class="alert-click-class">Click me!</a>', {html: true, timeout: 'none'});
```

Let me know if this helps.

**Comment by amnevins** [comment]
Thanks for your response!  I was not including {{>sAlert}} in my html.  The alerts were still showing but HTML classes were not firing events.  This is fixed now!  Thanks for the awesome work!
