### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by sangyoo91** [juliancwirko/meteor-s-alert#4]
I want to add a in custom templates.

And call it up by

sAlert.info('title','Your message');

How would I do this?

**Comment by juliancwirko** [comment]
Hi, you can pass the message by simple ````sAlert.info('Your message')```` and you can style it. 
I don't see exactly why you want to do this that way. Can you explain it more?

**Comment by juliancwirko** [comment]
If you want to add another field. There isn't way to do this like that. You should overwrite the template, and helper and populate it by yourself.

But it is a very good use case. I will think about it. I'll try to add such functionality.

**Comment by juliancwirko** [comment]
Hi, now (from version 1.2.0) you can achieve want you wanted. 
See 'template overwriting' section:
https://github.com/juliancwirko/meteor-s-alert#template-overwriting

and 'custom fields' section:
https://github.com/juliancwirko/meteor-s-alert#custom-fields

let me know if it helps.
