### ISSUE TITLE
Trigger notification

### ISSUE THREAD

**Issue by paulovale** [juliancwirko/meteor-s-alert#40]
Hi. I'm working on a app where a third party service adds rows to table. Is it possible to trigger the notification when the DOM element is added to the page?
Thanks

**Comment by juliancwirko** [comment]
It depends, s-alert is based on global sAlert functions so you need to fire `sAlert.success(...)` or other functions after your 'add-new-row' logic.

With Meteor you could use some ovservers on collections (http://docs.meteor.com/#/full/observe) etc. it all depends on how to use the logic which is responsible of adding new rows.

Anyway it should be handled in the project part not in the package. Package provides some global functions which will fire the alert with data and settings. It is up to you how you will consume that API.

**Comment by juliancwirko** [comment]
I close it for now. If you have more questions you can still comment here.
