### ISSUE TITLE
Create a native react component?

### ISSUE THREAD

**Issue by 416serg** [juliancwirko/meteor-s-alert#43]
It would be nice to remove blaze completely out of the package list

**Comment by juliancwirko** [comment]
I tought about it. It is based on local Meteor.Collection and Blaze templates right know. I probably could provide sAlert core and 2 other packages for Blaze and React. Also I wonder if we need this package at all when we want to use only React (or something) There are plenty similar packages on Npm which does the same.

For now it is very easy to use it with React stack, and I probably try to rebuild it to work with Blaze and React separately or maybe I will try to build React npm package without Meteor parts in it. 

Now it is a weird time. I don't know what will be the future of Atmosphere and Meteor packages at all ;)

**Comment by juliancwirko** [comment]
I am working on react-s-alert component. I hope I'll be able to rewrite all functionalities. It will be pure React Npm package and maybe Meteor wrapper package or I'll just wait for Meteor 1.3 and see how it could be integrated with new modules support in Meteor.

**Comment by juliancwirko** [comment]
For now I have pure React component which should be usable with new Meteor 1.3 Npm support. You'll find it here: https://github.com/juliancwirko/react-s-alert

**Comment by juliancwirko** [comment]
Ok it is done. For now I won't create Meteor Npm wrapper for it. I'll wait for Meteor 1.3 and then I'll test it.
Closing it for now. If you want you can still comment here.
