### ISSUE TITLE
Create an onclick event for the alert

### ISSUE THREAD

**Issue by chackerian** [juliancwirko/meteor-s-alert#49]
How can I execute a function when the user clicks on the sAlert?

**Comment by juliancwirko** [comment]
The simpler way is to just create new event for `sAlert` template in your app:

```javascript
Template.sAlert.events({
    'click .s-alert-box'() {
        console.log('test test');
    }
});
```

If you need you can also overwrite the template and create some buttons or links in the alert. You will find docs here: https://github.com/juliancwirko/meteor-s-alert#template-overwriting

**Comment by chackerian** [comment]
Thanks, that makes sense. Great work on the sAlert project.
