### ISSUE TITLE
Alert is autocleared on redirect 

### ISSUE THREAD

**Issue by buduguru** [juliancwirko/meteor-s-alert#5]
Hi.
The situation is:
1. user fills form and submits it.
2. After submit it is redirected to previous page with Router.go(...)
3. notification pops up

I use autoform plugin
and in `onSuccess` hook I add this code:
```javascript
   Router.go('redirectPage');
    sAlert.success('Success!',{effect: 'genie', position: 'right-bottom', timeout: 5000})
```
but after redirect the notification does not appear.

If I do it otherwise:

```javascript
   sAlert.success('Success!',{effect: 'genie', position: 'right-bottom', timeout: 5000})
   Router.go('redirectPage');
```

then notification appears, but is quickly autocleared because of redirection, so user sees it only for about 500ms which is very short.

I know that it is thought out like this, but in this particular case (form submission with redirect) it isn't OK.
Ideally it should appear right after submit and stay even after redirection for 2 sec or smth.

**Comment by juliancwirko** [comment]
Hmmm I think it is a proper behaviour for sAlert.
Here you should try different approach. You should call it in onAfterAction hook like for example:

```
AutoForm.hooks({
    myFormId: {
        onSuccess: function() {
            Session.set('isMyFormIdSuccessAlertSet', true);
            Router.go('/my-route-example');
        }
    }
});

Router.route('/my-route-example', {
    onAfterAction: function () {
        if (Session.equals('isMyFormIdSuccessAlertSet', true)) {
            sAlert.success('Success!',{effect: 'genie', position: 'right-bottom', timeout: 5000});
        }
        Session.set('isMyFormIdSuccessAlertSet', false);
    },
});
``` 
This is only an idea. I haven't tested it. But this is the way I probably would have chosen.

**Comment by buduguru** [comment]
Yes, it is reasonable. Thank you for a quick answer.
