### ISSUE TITLE
Problem when use with `alertifyjs`

### ISSUE THREAD

**Issue by thearabbit** [juliancwirko/meteor-s-alert#52]
I use `modal form` on `Alertify JS`.
So `s alert` show behind of `alertify modal`.

![2016-03-19_18-05-48](https://cloud.githubusercontent.com/assets/4495160/13898236/50f784b0-edfd-11e5-8f28-58a17ebb6f47.png)

**Comment by juliancwirko** [comment]
Yes, this is definatelly a problem with `z-index` Alertify JS uses z-index: 1981 and `.s-alert-box` has z-index: 1000 The solution is to set higher z-index on `.s-alert-box` class. You can do this in your app's stylesheet files. It should overwrite the value provided by styles in the package. So in your styles paste something like:

```css
.s-alert-box {
  z-index: 9999;
}
```
It should work, if not, check in google dev tools if .s-alert-box has overwritten z-index if not you can make sure that your styles overwrites it. I hope it helps. 

Maybe I should provide higher z-index in the package. I'll check what I can do with this.

**Comment by thearabbit** [comment]
Thanks, for your reply.
