### ISSUE TITLE
Hang when same message is sent.

### ISSUE THREAD

**Issue by mroftalp** [juliancwirko/meteor-s-alert#53]
` sAlert.info({createdBy: userId, message: message}, defaultSAlertParams);`
I notify like this ^ and works fine. But when I tried spamming with the same creator and same message and the app just hangs no error displayed on console. Then trying with different message it doesn't hang. Weird.

**Comment by juliancwirko** [comment]
Hi, this one is closed. Is this mean that it is not relevant anymore?

**Comment by mroftalp** [comment]
Yeah my bad
