### ISSUE TITLE
Introduce a delay?

### ISSUE THREAD

**Issue by nilsi** [juliancwirko/meteor-s-alert#59]
Hi,
I have an edit profile popup. When the user saves it closes the popup with a small animation. The s-alert then shows with a confirmation that the profile is saved but it pops up a bit to early before closing the popup finished totally. Is there any chance we could make a delay option to the settings to make the s-alert wait for a bit before it popups? Or should I simply put a timeout around the s-alert itself for situations like this?

**Comment by juliancwirko** [comment]
Hi, I think such actions should be managed by your custom code. It could be too much logic in the lib. You could create a simple timeout for this usecase.

**Comment by nilsi** [comment]
Okey no problem, just wanted to bring it up in case theres more people than me looking for this.
