### ISSUE TITLE
Make the package more lightweight?

### ISSUE THREAD

**Issue by voidale** [juliancwirko/meteor-s-alert#6]
`s-alert-effects.css` size is too much for alert package in my opinion should I just fork and remove the styles or maybe we can do something about it?

**Comment by juliancwirko** [comment]
Hi, I will try to clean it up more. There are all needed styles for all avaible alert effects. Maybe we should prepare separate packages for effects. I need to think about it.

Anyway It will be compressed in production. I don't think it should be a big problem. Of course you can fork the package. Or if you have any ideas how we should optimize it just drop a note here.
Thanks

**Comment by voidale** [comment]
@juliancwirko  Thank you, Sounds great. I will play with over the weekend if I find anything useful I will post here.

**Comment by juliancwirko** [comment]
Hey, you can check version 2.0.0: http://s-alert.meteor.com/
Now you can install only effects you realy want. You can also write and add your custom ones.

**Comment by voidale** [comment]
Wow awesome! You're really quick, It's great thanks a lot.
