### ISSUE TITLE
I can not increase the size of the box

### ISSUE THREAD

**Issue by vichiodo** [juliancwirko/meteor-s-alert#61]
Hello,

I created a custom alert and I need it to be bigger than normal but I'm changing the width attribute and nothing happenning, it still with the same size. Could you help me, please??? Thank you!!!

**Comment by juliancwirko** [comment]
Hi, do you mean width in css styles? Do you have demo to show?

**Comment by vichiodo** [comment]
Yes in is the width in css. My code is like this.

`.custom-alert-class {
	background: white;
	color: black;
	border: 1px solid #D7D7D7;
	height: 70px;
	width: 400px;
	font-size: 16px;
}`

e meu html
`<template name="sAlertCustom">
    <div class="custom-alert-class s-alert-box s-alert-{{condition}} s-alert-{{position}} s-alert-effect-{{effect}} s-alert-show" id="{{_id}}" style="{{boxPosition}}">
        <div class="s-alert-box-inner">
            <div class="alert-header">
				<i class="fa fa-{{sAlertIcon}}" aria-hidden="true"></i>
				{{#if sAlertTitle}}
					<h1>{{sAlertTitle}}</h1>				
				{{/if}}
            </div>
            <div class="alert-content">
                <p>{{message}}</p>
				
            </div>
        </div>
    </div>
</template>`

I change the width but nothing really change. Do you know why?

**Comment by juliancwirko** [comment]
Oh, ok try to add  `max-width: 400px` in `custom-alert-class`

**Comment by vichiodo** [comment]
It's almost there but it doesn't get longer than 400px. I wanted the message on the side of the icon and I have messages bigger than that.

![image](https://cloud.githubusercontent.com/assets/8626734/22345964/6a75e84a-e3e9-11e6-9323-943df1b1211b.png)

**Comment by juliancwirko** [comment]
Ok, so you need to adjust the css. The main css styles are in `s-alert-box` in this case you need to specify `max-width: none` and `width: auto` in your custom class. I hope it will help. But you will get different sizes depending on the length of the message.

**Comment by vichiodo** [comment]
Ooow it worked!!! Like this I can set an especific value for width. Thank you soooo much!!!!!!
