### ISSUE TITLE
Common English names for positions

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#8]
"bottom-left", "bottom-right", "top-left" and "top-right" are more commonly used than the current names ("left-top" etc.). Maybe add the common English corner names as synonyms? Optionally the current positions names could be marked as deprecated.

**Comment by juliancwirko** [comment]
Good point. I will try to change it, and provide some kind of deprecation solution.

**Comment by juliancwirko** [comment]
Ok, it is done in v2.1.0

**Comment by dandv** [comment]
Works great. Thanks!
