### ISSUE TITLE
Full-width top or bottom position

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#9]
I'm looking for an effect like stackslide, but with different animations:

* occupy the entire width of the screen (useful on mobile)
* be placed at the top or bottom (the [Available positions](https://github.com/juliancwirko/meteor-s-alert#avaible-positions) are only corners right now)
* animation like `scale`, `slide` from left/right, `genie`, `jelly` or `bouncyflip`

I've managed to do this by adding a custom CSS rule `min-width: 100%`. Should there be a better way? Maybe specifying `position` without `left` or `right`, but just as `top` or `bottom`?

**Comment by juliancwirko** [comment]
Ok, I see what you mean. This is a very good idea for cleaning and reafactor. I think that we could have two more position indicators `top` `bottom` (full width) for all effects types.

**Comment by juliancwirko** [comment]
Ok, it is done in v2.1.0

**Comment by dandv** [comment]
After updating both the main package and the effects one(s), this works great! Thanks!
